version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ProcureX_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aadil@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: prod

volumes:
  postgres_data: