spring:
  application:
    name: procurex-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ProcureX_DB
    username: postgres
    password: aadil@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  address: 0.0.0.0
  port: 8080
